using Newtonsoft.Json;
using System.Text;

namespace Lab8.Client
{
    class Program
    {
        static async Task Main(string[] args)
        {

            RequestSender sender = new();

            //Matrix generated by the back-end
            //await sender.sendWithSize();


            //Matrix generated by the client
            await sender.sendWithMatrix();
        }
    }
}
